name: First CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Check lesson2 files
        run: |
          test -f lesson2/index.html
          test -f lesson2/Containerfile
          echo "Required files exist!"

      - name: Build container image
        run: |
          cd lesson2
          podman build -t my-first-web .